### ISSUE TITLE
Do you know where can I get an open source program for mobile app energy?

### ISSUE THREAD

**Issue by SakuraXiaMF** [luiscruz/awesome-mobile-app-energy-papers#2]
I am a newly enrolled Ph.D. student. I have an idea at the mobile app energy area, but I don't how to get a program with basic mobile app energy controller function.

**Comment by luiscruz** [comment]
Hi Sakura, thanks for reaching me out with questions on mobile/energy. I'll be happy to help.
Please send me an email clarifying what kind of program you need exactly.
You can find my email address in my profile page.

I'll close this issue since it is not directly related with the repo. Best.
